# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

def shared_pods
	pod 'AFNetworking', '~> 2.5'
	#pod 'RZImport', '~> 1.0'
    	#pod 'RZVinyl', :git=> 'git@github.com:Raizlabs/RZVinyl.git', :commit=> '179e21b10d10d41635bbaa505ae974139d3a0ec9'
end

target 'Requester' do
	shared_pods
end

target 'RequesterTests' do
	shared_pods
end

